### ISSUE TITLE
Parsing CSV file 

### ISSUE THREAD

**Issue by davitjnz** [ibex-app/frontend#7]
Extract information from uploaded csv file

**Comment by aquarazorda** [comment]
We might need to add parsing in the backend and then send it as a JSON to frontend.

Doing simple searches, I can find that, it's not an issue to create CSV file from React, but parsing it might not be possible.
It needs a deeper research.

**Comment by aquarazorda** [comment]
Impelemnted here 1f330591bb972f324ca9abae64098135455aa42f
